var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/features/story-mention/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t3m05t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0shh6z2.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q00nxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gwfb7v._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_features_story-mention_layout_jsx_0x0_jgk._.js")
R.c("server/chunks/ssr/_next-internal_server_app_features_story-mention_page_actions_0ghkz.7.js")
R.m(53674)
module.exports=R.m(53674).exports
