var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/support/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__06l0ec_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0rhl_lj.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q00nxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gwfb7v._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_dashboard_layout_jsx_13~cnr3._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_support_page_actions_0r9.9ts.js")
R.m(9312)
module.exports=R.m(9312).exports
