var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/sitemap/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00l5-73._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0b6b46a.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q00nxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/_0v9580k._.js")
R.c("server/chunks/ssr/_09fjaw~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_sitemap_page_actions_0ee69_i.js")
R.m(98100)
module.exports=R.m(98100).exports
