var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/magic-setup/route.js")
R.c("server/chunks/[root-of-the-server]__0bsiuvc._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_070ngqb.js")
R.c("server/chunks/[root-of-the-server]__01r432a._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/node_modules_groq-sdk_index_mjs_0xg394.._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_magic-setup_route_actions_0iqxhcd.js")
R.m(36209)
module.exports=R.m(36209).exports
