var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/compare/[competitor]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0w03lt1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ytobno.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q00nxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/_10._c6z._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_compare_[competitor]_layout_jsx_13o8nyg._.js")
R.c("server/chunks/ssr/_next-internal_server_app_compare_[competitor]_page_actions_0lbhkt6.js")
R.m(63002)
module.exports=R.m(63002).exports
