var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/callback/facebook/route.js")
R.c("server/chunks/_13n8f9l._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/[root-of-the-server]__0ldd600._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/[root-of-the-server]__01r432a._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_callback_facebook_route_actions_08usfcg.js")
R.m(93435)
module.exports=R.m(93435).exports
