var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/automation/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__10fqych._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0sumbm7.js")
R.c("server/chunks/ssr/node_modules_next_dist_06u0kr8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0h5tz8r._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-u0owa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/_0v9580k._.js")
R.c("server/chunks/ssr/_09fjaw~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_dashboard_layout_jsx_13~cnr3._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_automation_[id]_page_actions_0k_uxmu.js")
R.m(12525)
module.exports=R.m(12525).exports
