var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/features/comment-auto-responder/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_jfzvb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06u0kr8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0u~_p-h.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-u0owa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/_0v9580k._.js")
R.c("server/chunks/ssr/_09fjaw~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_features_comment-auto-responder_layout_jsx_0s8x~7~._.js")
R.c("server/chunks/ssr/_next-internal_server_app_features_comment-auto-responder_page_actions_11nhoq~.js")
R.m(86259)
module.exports=R.m(86259).exports
