var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/features/dm-auto-reply/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vjiy2-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0bkn9j0.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q00nxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/_10._c6z._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_features_dm-auto-reply_layout_jsx_12q8.0.._.js")
R.c("server/chunks/ssr/_next-internal_server_app_features_dm-auto-reply_page_actions_0h8zg_1.js")
R.m(19498)
module.exports=R.m(19498).exports
