var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/compare/[competitor]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gwg2pa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06u0kr8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_00sy1fh.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-u0owa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/_0v9580k._.js")
R.c("server/chunks/ssr/_09fjaw~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_compare_[competitor]_layout_jsx_13o8nyg._.js")
R.c("server/chunks/ssr/_next-internal_server_app_compare_[competitor]_page_actions_0lbhkt6.js")
R.m(11518)
module.exports=R.m(11518).exports
