var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/webhook/route.js")
R.c("server/chunks/[root-of-the-server]__01aw4cv._.js")
R.c("server/chunks/_13n8f9l._.js")
R.c("server/chunks/node_modules_groq-sdk_index_mjs_0xg394.._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_02xh0~a.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/_0xu6~91._.js")
R.c("server/chunks/[root-of-the-server]__01r432a._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_webhook_route_actions_0pc1eu8.js")
R.m(66924)
module.exports=R.m(66924).exports
