var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/checkout/create/route.js")
R.c("server/chunks/[root-of-the-server]__0kpkslf._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_13n8f9l._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/[root-of-the-server]__01r432a._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/[root-of-the-server]__0b2uvty._.js")
R.c("server/chunks/_next-internal_server_app_api_checkout_create_route_actions_0l5w978.js")
R.m(36745)
module.exports=R.m(36745).exports
