var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/solutions/brands/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a0j19z._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0r.v1ky.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q00nxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gwfb7v._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_solutions_brands_layout_jsx_0d9l3q3._.js")
R.c("server/chunks/ssr/_next-internal_server_app_solutions_brands_page_actions_09~kpj8.js")
R.m(64563)
module.exports=R.m(64563).exports
