var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/checkout/success/route.js")
R.c("server/chunks/[root-of-the-server]__10sn7k-._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/[root-of-the-server]__01r432a._.js")
R.c("server/chunks/_0xu6~91._.js")
R.c("server/chunks/_next-internal_server_app_api_checkout_success_route_actions_0q62u5s.js")
R.m(97253)
module.exports=R.m(97253).exports
