var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/shield/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__038bvug._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_117wrpo.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q00nxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gwfb7v._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_shield_layout_tsx_10sc~m_._.js")
R.c("server/chunks/ssr/_next-internal_server_app_shield_page_actions_0p3ikw2.js")
R.m(22605)
module.exports=R.m(22605).exports
