// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/data-deletion" | "/privacy" | "/shield" | "/terms"
type AppRouteHandlerRoutes = "/api/ai/autofill" | "/api/ai/magic-setup" | "/api/auth/callback" | "/api/auth/callback/facebook" | "/api/auth/connect" | "/api/checkout/create" | "/api/checkout/success" | "/api/media" | "/api/media/sync" | "/api/media/test-simulate" | "/api/webhook" | "/api/webhooks/test" | "/api/workspaces/invite" | "/llms.txt"
type PageRoutes = never
type LayoutRoutes = "/" | "/blog" | "/compare/[competitor]" | "/contact" | "/dashboard" | "/data-deletion" | "/features/comment-auto-responder" | "/features/dm-auto-reply" | "/features/story-mention" | "/partners" | "/pricing" | "/shield" | "/solutions/brands" | "/solutions/creators"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/autofill": {}
  "/api/ai/magic-setup": {}
  "/api/auth/callback": {}
  "/api/auth/callback/facebook": {}
  "/api/auth/connect": {}
  "/api/checkout/create": {}
  "/api/checkout/success": {}
  "/api/media": {}
  "/api/media/sync": {}
  "/api/media/test-simulate": {}
  "/api/webhook": {}
  "/api/webhooks/test": {}
  "/api/workspaces/invite": {}
  "/blog": {}
  "/compare/[competitor]": { "competitor": string; }
  "/contact": {}
  "/dashboard": {}
  "/data-deletion": {}
  "/features/comment-auto-responder": {}
  "/features/dm-auto-reply": {}
  "/features/story-mention": {}
  "/llms.txt": {}
  "/partners": {}
  "/pricing": {}
  "/privacy": {}
  "/shield": {}
  "/solutions/brands": {}
  "/solutions/creators": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/blog": never
  "/compare/[competitor]": never
  "/contact": never
  "/dashboard": never
  "/data-deletion": never
  "/features/comment-auto-responder": never
  "/features/dm-auto-reply": never
  "/features/story-mention": never
  "/partners": never
  "/pricing": never
  "/shield": never
  "/solutions/brands": never
  "/solutions/creators": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
